font_family  FiraCode Nerd Font
bold_font  FiraCode Nerd Font
italic_font  FiraCode Nerd Font
font_size  14

background #000000
foreground #ffffff

selection_background #ffffff
selection_foreground #000000

shell_integration no-cursor
cursor_shape block

tab_bar_edge top
tab_bar_style powerline
tab_powerline_style round
map ctrl+shift+t new_tab_with_cwd

color0 #171421
color1 #C01C28
color2 #26A269
color3 #A2734C
color4 #12488B
color5 #A347BA
color6 #2AA1B3
color7 #D0CFCC
color8 #5E5C64
color9 #F66151
color10 #33D17A
color11 #E9AD0C
color12 #2A7BDE
color13 #C061CB
color14 #33C7DE
color15 #FFFFFF

#: }}}
